version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install

  build:
    commands:
      # 1) Grab current production version
      - |
        PREVIOUS_VERSION=$(aws lambda get-alias \
          --function-name ${LAMBDA_NAME} \
          --name production \
          --query FunctionVersion \
          --output text)

      # 2) Zip the codde
      - zip -r code.zip .

      # And push the new code to the lambda
      - aws lambda update-function-code --function-name ${LAMBDA_NAME} --zip-file fileb://./code.zip

      # Remove so it is not included in the next stpe zip.
      - rm code.zip

      # Wait for the code update before doing anything else.
      - aws lambda wait function-updated --function-name ${LAMBDA_NAME}

      # 2) Publish new version
      - |
        NEW_VERSION=$(aws lambda publish-version \
          --function-name ${LAMBDA_NAME} \
          --query Version \
          --output text)

      # Validating appspec.yml
      - |
        for prop in Name CurrentVersion TargetVersion; do
          grep -q "^ *${prop}:" .aws/code_deploy/appspec.yml || { echo "Error: ${prop} missing in appspec.yml"; exit 1; }
        done

      # 4) Generate appspec.yml with a literal block
      - |
        sed -i \
          -e "s/__FUNCTION_NAME__/${LAMBDA_NAME}/" \
          -e "s/__PREVIOUS_VERSION__/${PREVIOUS_VERSION}/" \
          -e "s/__NEW_VERSION__/${NEW_VERSION}/" \
        .aws/code_deploy/appspec.yml

      # 5) Debug
      - cat .aws/code_deploy/appspec.yml

artifacts:
  files:
    - "**/*"
  base-directory: .aws/code_deploy
